base:
  project: satellite-segmentation
  random_seed: 42

data:
  hf_dataset: "keremberke/satellite-building-segmentation"
  subset: 1.0           # Use 1.0 for full training
  img_size: 500         # Fixed input size
  processed_dir: "data/processed"
  
  # Splits
  train_ratio: 0.7
  val_ratio: 0.2
  test_ratio: 0.1

train:
  # Options: "yolo" (Transfer Learning) or "custom" (Own Architecture)
  model_type: "custom" 
  
  # Common settings
  epochs: 5
  batch_size: 4
  img_size: 500
  device: 0
  workers: 8
  
  # Model A: YOLO Specifics
  yolo_config:
    model_name: "yolov8m-seg.pt"
    optimizer: "AdamW"
    lr0: 0.001

  # Model B: Custom Architecture Specifics
  custom_config:
    learning_rate: 0.0001
    optimizer: "Adam" # Custom often prefers standard Adam
    # We will save best weights here
    save_path: "runs/custom_model/weights/best.pth"
  
  # Online Augmentations (Applied by YOLO every epoch)
  augment:
    degrees: 90.0      # Random rotation +/- 90 degrees
    fliplr: 0.5        # 50% chance horizontal flip
    flipud: 0.5        # 50% chance vertical flip (Satellite views allow this!)
    scale: 0.5         # Zoom in/out (+/- 50%)
    mosaic: 1.0        # Use Mosaic (stitches 4 images together) - Crucial for small objects
    hsv_h: 0.015       # Color jitter (Hue)
    hsv_s: 0.7         # Color jitter (Saturation)
    hsv_v: 0.4         # Color jitter (Value/Brightness)