base:
  project: satellite-segmentation
  random_seed: 42

data:
  hf_dataset: "keremberke/satellite-building-segmentation"
  subset: 1.0           # Use 1.0 for full training
  img_size: 500         # Fixed input size
  processed_dir: "data/processed"
  
  # Splits
  train_ratio: 0.7
  val_ratio: 0.2
  test_ratio: 0.1

train:
  # Choose Model: "transfer" or "custom"
  model_type: "custom" 
  
  # Hyperparameters
  epochs: 5
  batch_size: 4
  workers: 4
  
  # Configuration for your Custom Architecture
  custom_config:
    learning_rate: 0.0001
    optimizer: "Adam"
    save_path: "runs/custom_model/weights/best.pth"
  
  # Configuration for Transfer Learning (Baseline)
  transfer_config:
    learning_rate: 0.0015 # Pre-trained models often need higher initial LR
    optimizer: "AdamW"
  
  # Augmentations (Albumentations)
  augment:
    degrees: 90.0      
    fliplr: 0.5        
    flipud: 0.5        
    scale: 0.5         
    hsv_h: 0.015       
    hsv_s: 0.7         
    hsv_v: 0.4